version: "3"

services:
  inventory_App:
    container_name: inventory_App
    image: postgres
    environment:
      POSTGRES_USER: "inventory_user_me"
      POSTGRES_PASSWORD: "inventory1234"
      PGDATA: /data/inventory_app
    volumes:
      - inventory_app:/data/inventory_app
    ports:
      - "5434:5432"
    networks:
      - inventory_app_net
    restart: unless-stopped

networks:
  inventory_app_net:
    driver: bridge

volumes:
  inventory_app: